export interface Usuario {
  id: number;
  nombre?: string | null;
  edad?: number | null;
  altura?: number | null;
  peso?: number | null;
  metabolismo?: number | null;
}

export interface Comida {
  id: number;
  nombre: string;
  valor_calorico?: number | null;
  descripcion?: string | null;
}

export interface Ruta {
  id: number;
  usuario_id: number;
  fecha: string;
  distancia?: number | null;
  coordenadas?: string | null;
}

export interface Consumo {
  id: number;
  usuario_id: number;
  comida_id: number;
  fecha: string;
  cantidad?: number;
}

export type NewUsuario = Omit<Usuario, 'id'>;
export type NewComida = Omit<Comida, 'id'>;
export type NewRuta = Omit<Ruta, 'id'>;
// Make fecha optional as it's generated by the addConsumption function
export type NewConsumo = Omit<Consumo, 'id' | 'fecha'> & { fecha?: string };